apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/sajil143pb/jenkins.git
    path: wordpress_application/EKS/wordpress
    targetRevision: HEAD

  destination:
    server: https://kubernetes.default.svc
    namespace: wordpress-app

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    
    automated:
      prune: true
      selfHeal: true
  
