apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/sajil143pb/jenkins.git
    path: java_eks_helm_argo/Argocd/myapp
    targetRevision: HEAD

  destination:
    server: https://kubernetes.default.svc
    namespace: demo-app

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    
    automated:
      prune: true
      selfHeal: true
  
